CREATE TABLE IF NOT EXISTS users(
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) UNIQUE,
password VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS profile(
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) UNIQUE,
name VARCHAR(100) NOT NULL,
age INT NOT NULL,
qualification VARCHAR(100) NOT NULL,
phone VARCHAR(20) NOT NULL,
gender VARCHAR(20) NOT NULL,
location VARCHAR(100) NOT NULL,
hobby TEXT,
preferred_job_type VARCHAR(50),
experience_level VARCHAR(50),
skills_text TEXT,
resume TEXT NOT NULL
);
